language: smalltalk
sudo: false
os:
  - linux
smalltalk_edge:
  source: hpi-swa/smalltalkCI
  branch: dev
jobs:
  includes:
    - smalltalk: Pharo-6.1
    smalltalk_config: .smalltalk-pharo61.ston
    - smalltalk: Pharo-7.0

smalltalk_config: .smalltalk.ston
