Extension { #name : #ClySystemEnvironmentPlugin }

{ #category : #'*Calypso-ProcessQueries' }
ClySystemEnvironmentPlugin >> collectMetadataOfContexts: anEnvironmentContent [
]

{ #category : #'*Calypso-ProcessQueries' }
ClySystemEnvironmentPlugin >> collectMetadataOfProcesses: anEnvironmentContent [
]

{ #category : #'*Calypso-ProcessQueries' }
ClySystemEnvironmentPlugin >> prepareBrowserItem: anItem ofContext: aContext [
]

{ #category : #'*Calypso-ProcessQueries' }
ClySystemEnvironmentPlugin >> prepareBrowserItem: anItem ofProcess: aProcess [
]
