SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Browser'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Browser-Breakpoints'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Browser-Commands'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Browser-ExecutionCounters'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Browser-Watchpoints'!
