SystemOrganization addCategory: #'Calypso-Environment-System'!
SystemOrganization addCategory: 'Calypso-Environment-System-Content'!
SystemOrganization addCategory: 'Calypso-Environment-System-Domain'!
SystemOrganization addCategory: 'Calypso-Environment-System-Properties'!
SystemOrganization addCategory: 'Calypso-Environment-System-Queries'!
SystemOrganization addCategory: 'Calypso-Environment-System-Scopes'!
