SystemOrganization addCategory: #'Calypso-SystemTools-FullBrowser'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Commands-Class groups'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Commands-Classes'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Commands-Hierarchy'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Commands-MetaLevel'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Commands-MethodGroups'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Commands-Methods'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Commands-Packages'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Contexts'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-Toolbar'!
SystemOrganization addCategory: 'Calypso-SystemTools-FullBrowser-UI'!
