SystemOrganization addCategory: #'Calypso-SystemTools-Core'!
SystemOrganization addCategory: 'Calypso-SystemTools-Core-Commands-Classes'!
SystemOrganization addCategory: 'Calypso-SystemTools-Core-Commands-Methods'!
SystemOrganization addCategory: 'Calypso-SystemTools-Core-Commands-Queries'!
SystemOrganization addCategory: 'Calypso-SystemTools-Core-Contexts'!
SystemOrganization addCategory: 'Calypso-SystemTools-Core-Editors-Classes'!
SystemOrganization addCategory: 'Calypso-SystemTools-Core-Editors-Methods'!
SystemOrganization addCategory: 'Calypso-SystemTools-Core-TableDecorators'!
