SystemOrganization addCategory: #'Calypso-Tools-SystemBrowser'!
SystemOrganization addCategory: 'Calypso-Tools-SystemBrowser-Commands-Methods'!
SystemOrganization addCategory: 'Calypso-Tools-SystemBrowser-Commands-Queries'!
SystemOrganization addCategory: 'Calypso-Tools-SystemBrowser-Contexts'!
SystemOrganization addCategory: 'Calypso-Tools-SystemBrowser-Editors-Methods'!
SystemOrganization addCategory: 'Calypso-Tools-SystemBrowser-TableDecorators'!
