SystemOrganization addCategory: #'Calypso-SystemTools-QueryBrowser'!
SystemOrganization addCategory: #'Calypso-SystemTools-QueryBrowser-Commands-Controlling'!
SystemOrganization addCategory: #'Calypso-SystemTools-QueryBrowser-Commands-Methods'!
SystemOrganization addCategory: #'Calypso-SystemTools-QueryBrowser-Commands-Queries'!
SystemOrganization addCategory: #'Calypso-SystemTools-QueryBrowser-UI'!
