SystemOrganization addCategory: #'Calypso-SystemTools-PackageBrowser'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Commands-Class groups'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Commands-Classes'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Commands-Hierarchy'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Commands-MetaLevel'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Commands-MethodGroups'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Commands-Methods'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Commands-Packages'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Contexts'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-Toolbar'!
SystemOrganization addCategory: 'Calypso-SystemTools-PackageBrowser-UI'!
