SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Queries'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Queries-Breakpoints'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Queries-ExecutionCounters'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Queries-Plugin'!
SystemOrganization addCategory: #'Calypso-SystemPlugins-Reflectivity-Queries-Watchpoints'!
